### ISSUE TITLE
With katello-removal we have 31 test failures now

### ISSUE THREAD

**Issue by chris1984** [theforeman/foreman_rh_cloud#836]
```ruby
Error:
ArchivedReportGeneratorTest#test_0001_generates a report for a single host:
NoMethodError: undefined method `katello_agent_installed?' for #<Katello::Host::ContentFacet:0x000055ea643520d8>
    /home/vagrant/foreman_rh_cloud/lib/foreman_inventory_upload/generators/slice.rb:130:in `report_system_profile'
    /home/vagrant/foreman_rh_cloud/lib/foreman_inventory_upload/generators/slice.rb:56:in `block (2 levels) in report_host'
    /home/vagrant/foreman_rh_cloud/lib/foreman_inventory_upload/generators/json_stream.rb:17:in `object'
    /home/vagrant/foreman_rh_cloud/lib/foreman_inventory_upload/generators/json_stream.rb:56:in `object_field'
    /home/vagrant/foreman_rh_cloud/lib/foreman_inventory_upload/generators/slice.rb:55:in `block in report_host'
    /home/vagrant/foreman_rh_cloud/lib/foreman_inventory_upload/generators/json_stream.rb:17:in `object'
    /home/vagrant/foreman_rh_cloud/lib/foreman_inventory_upload/generators/slice.rb:45:in `report_host'
    /home/vagrant/foreman_rh_cloud/lib/foreman_inventory_upload/generators/slice.rb:34:in `block (3 levels) in report_slice'
```

**Comment by evgeni** [comment]
Should be fixed since https://github.com/theforeman/foreman_rh_cloud/commit/02e5b9e7e6c72b559006abde7d15b2f59b7767fe, right?

**Comment by chris1984** [comment]
Fixed with https://github.com/theforeman/foreman_rh_cloud/commit/02e5b9e7e6c72b559006abde7d15b2f59b7767fe
